server:
  port: 8082
#激活账户后返回的主界面的地址值
font:
  url: http://www.baidu.com
spring:
  application:
    name: identity_service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.66.183:3306/logistics_tp?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: emiya
    password: imouto949
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 3
    host: 111.229.66.183
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 50
        max-wait: -1ms
        min-idle: 50
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    username: thulium0601@163.com
    password: NSKVWIQLNQFXJHZD
    host: smtp.163.com
mybatis-plus:
  mapper-locations: classpath:com/tiandi/logistics/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)z
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
